### ISSUE TITLE
CurrentSetting and DeviceList (AttachedDevices) not parsed correctly

### ISSUE THREAD

**Issue by Ikon79** [gruijter/com.gruijter.netgear#29]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.6.0
OS: linux 4.14.15-g81f15bab94
t = 0
trying to auto discover Netgear routers...
[{host:192.168.1.1,port:5000}]
t = 4.072
trying to login...
login method: 1
t = 4.158
trying to getInfo...
{ModelName:R6800,Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.2.0.42,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Hardwareversion:R6800,Otherhardwareversion:N/A,FirstUseDate:Wednesday, 05 June 2019 22:33:22,DeviceName:R6800,FirmwareDLmethod:HTTPS,FirmwareLastUpdate:2019_6.3_17:20:38,FirmwareLastChecked:2019_6.5_22:27:12,DeviceMode:0}
t = 4.26
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,SmartConnect:2.0,AttachedDevice:2.0,NameNTGRDevice:1.0,TimeZone:2.0,MaxMonthlyTrafficLimitation:4095000000}
t = 4.347
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewTimeZone:+01,NewDaylightSaving:1}
t = 4.433
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewLANIP:192.168.1.1,NewDHCPEnabled:1,NewWANLAN_Subnet_Match:0,NewLANMACAddress:8C3BAD3A0074}
t = 4.521
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:87.96.252.216,NewSubnetMask:255.255.254.0,NewAddressingType:DHCP,NewDefaultGateway:87.96.252.1,NewMACAddress:8C3BAD3A0076,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:87.96.146.227 87.96.146.211 8.8.8.8}
t = 4.613
trying to get Parental Control Status...
Parental Control Enabled: false
t = 5.105
trying to get Qos Status...
Qos Enabled: false
t = 5.595
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:1}
t = 5.674
trying to get Device Access Control Status...
Block Device Enabled: true
t = 5.765
trying to get attachedDevices...
Number of attached devices: 11, method: 2
First attached device: {\IP\:\192.168.1.2\,\Name\:\IKONS-IPAD\,\NameUserSet\:false,\MAC\:\84:B1:53:5C:25:08\,\ConnectionType\:\2.4GHz\,\SSID\:\Ikon\,\Linkspeed\:130,\SignalStrength\:96,\AllowOrBlock\:\Allow\,\Schedule\:false,\DeviceTypeUserSet\:false,\Grouping\:0,\SchedulePeriod\:0}
t = 5.946
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 6.26
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 7.11
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 7.19
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 7.273
trying to get trafficMeter...
{newTodayUpload:10362.89,newTodayDownload:6178.48,newMonthUpload:45285.37,newMonthDownload:77463.18}
t = 7.37
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:V1.2.0.42,newVersion:,releaseNote:}
t = 9.517
trying to logout...
{host:192.168.1.1,port:5000,username:admin,password:*****,timeout:19000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:2,loginMethod:1,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
t = 9.594
test finished without errors :)

**Comment by gruijter** [comment]
Well, everything ok here! Could you post the app logs? Maybe I see something there.

**Comment by Ikon79** [comment]
Only thing I saw whit logs, but I guess this isn’t what u meant

2019-06-05 23:40:36 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:40:16 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:39:56 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:39:36 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:39:16 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:38:56 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:38:36 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:38:16 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:37:56 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:37:36 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:37:16 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:36:57 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:36:36 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:36:16 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:35:56 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:35:36 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:35:16 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:34:57 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:34:36 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:34:16 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:33:56 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:33:37 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:33:16 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:32:56 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined 
2019-06-05 23:32:36 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Cannot read property 'toLowerCase' of undefined

**Comment by gruijter** [comment]
Yes this is what I needed. There is a problem here that I need to look into. Maybe  I have some time this weekend.

**Comment by Ikon79** [comment]
Ok, thx😃. 
Will you get back to me when u’ve checked it out?

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
Off course I will update here🤗

Can you browse to http://routerlogin.net/currentsetting.htm (while connected to the router) and paste the result here?

**Comment by Ikon79** [comment]
firmware=V1.2.0.42_1.0.1WW RegionTag=R6800_WW Region=WW Model=R6800 InternetConnectionStatus=UP ParentalControlSupported=1 SOAPVersion=3.21 ReadyShareSupportedLevel=29 XCloudSupported=1 LoginMethod=2.0

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
v2.5.4  2019.06.06 Fix parsing currentSetting for R6800.

The new version is waiting approval in the Appstore. If you know how to sideload, you can already install and test from github now.

**Comment by Ikon79** [comment]
Thx for your reply 

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
Hi Anders,

v2.5.4 was just released in the appstore. Can you please test and post the testresults again?

Thx!
Robin

**Comment by Ikon79** [comment]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.6.1
OS: linux 4.14.15-g81f15bab94
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.2.0.42_1.0.1WW,RegionTag:R6800_WW,Region:WW,Model:R6800,InternetConnectionStatus:UP,ParentalControlSupported:1,SOAPVersion:3.21,ReadyShareSupportedLevel:29,XCloudSupported:1,LoginMethod:2.0,host:192.168.1.1,port:5000}]
t = 4.168
trying to login...
login method: 2
t = 4.277
trying to getInfo...
{ModelName:R6800,Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.2.0.42,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Hardwareversion:R6800,Otherhardwareversion:N/A,FirstUseDate:Friday, 07 June 2019 16:06:44,DeviceName:R6800,FirmwareDLmethod:HTTPS,FirmwareLastUpdate:2019_6.3_17:20:38,FirmwareLastChecked:2019_6.7_15:42:49,DeviceMode:0}
t = 4.378
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,SmartConnect:2.0,AttachedDevice:2.0,NameNTGRDevice:1.0,TimeZone:2.0,MaxMonthlyTrafficLimitation:4095000000}
t = 5.117
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewTimeZone:+01,NewDaylightSaving:1}
t = 5.201
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewLANIP:192.168.1.1,NewDHCPEnabled:1,NewWANLAN_Subnet_Match:0,NewLANMACAddress:8C3BAD3A0074}
t = 5.279
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:87.96.252.216,NewSubnetMask:255.255.254.0,NewAddressingType:DHCP,NewDefaultGateway:87.96.252.1,NewMACAddress:8C3BAD3A0076,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:87.96.146.227 87.96.146.211 8.8.8.8}
t = 6.028
trying to get Parental Control Status...
Parental Control Enabled: false
t = 6.523
trying to get Qos Status...
Qos Enabled: false
t = 7.688
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:1}
t = 7.828
trying to get Device Access Control Status...
Block Device Enabled: true
t = 8.574
trying to get attachedDevices...
Number of attached devices: 11, method: 2
First attached device: {\IP\:\192.168.1.2\,\Name\:\IKONS-IPAD\,\NameUserSet\:false,\MAC\:\84:B1:53:5C:25:08\,\ConnectionType\:\5GHz\,\SSID\:\Ikon 5\,\Linkspeed\:242,\SignalStrength\:15,\AllowOrBlock\:\Allow\,\Schedule\:false,\DeviceTypeUserSet\:false,\Grouping\:0,\SchedulePeriod\:0}
t = 9.379
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 11.66
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 12.807
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 12.885
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 12.964
trying to get trafficMeter...
{newTodayUpload:4218.02,newTodayDownload:20070.35,newMonthUpload:63222.4,newMonthDownload:117894.13}
t = 13.727
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:V1.2.0.42,newVersion:,releaseNote:}
t = 15.867
trying to logout...
{host:192.168.1.1,port:5000,username:admin,password:*****,timeout:19000,sessionId:A7D88AE69687E58D9A00,cookie:[Token=cfec622202daa212],loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
t = 15.934
test finished without errors :)

**Comment by gruijter** [comment]
Looks good! Can you confirm the app is now fully working for your R6800?

**Comment by Ikon79** [comment]
Seems to update live now, so i guess it works as it should


Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
Super! Great that it is solved. Let me know if new issues pop up.
cheers.

**Comment by Ikon79** [comment]
It doesn’t seem to update my device list thou, it still says 9 days on that

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
Can you post the app logs again?

**Comment by Ikon79** [comment]
2019-06-07 19:15:05 [log] [ManagerDrivers] [netgear] [0] login succsesfull @ driver 
2019-06-07 19:14:45 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in 
2019-06-07 19:14:45 [log] [ManagerDrivers] [netgear] [0] "\r\n\r\n\r\n  401\r\n\r\n\r\n" 
2019-06-07 19:14:45 [log] [ManagerDrivers] [netgear] [0] last repsonse from router: 
2019-06-07 18:19:44 [log] [ManagerDrivers] [netgear] [0] login succsesfull @ driver 
2019-06-07 18:19:24 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in 
2019-06-07 18:19:24 [log] [ManagerDrivers] [netgear] [0] "\r\n\r\n\r\n  401\r\n\r\n\r\n" 
2019-06-07 18:19:24 [log] [ManagerDrivers] [netgear] [0] last repsonse from router: 
2019-06-07 17:24:23 [log] [ManagerDrivers] [netgear] [0] login succsesfull @ driver 
2019-06-07 17:24:03 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in 
2019-06-07 17:24:03 [log] [ManagerDrivers] [netgear] [0] "\r\n\r\n\r\n  401\r\n\r\n\r\n" 
2019-06-07 17:24:03 [log] [ManagerDrivers] [netgear] [0] last repsonse from router: 
2019-06-07 16:33:23 [log] [ManagerDrivers] [netgear] [0] Offline: E4:A7:A0:27:53:BC GT-6341HKJ 
2019-06-07 16:32:23 [log] [ManagerDrivers] [netgear] [0] Online: E4:A7:A0:27:53:BC GT-6341HKJ 192.168.1.13 
2019-06-07 16:29:01 [log] [ManagerDrivers] [netgear] [0] Access control enable requested 
2019-06-07 16:28:49 [log] [MyApp] app unload called 
2019-06-07 16:17:50 [log] [ManagerDrivers] [netgear] [0] the internet connection came up 
2019-06-07 16:17:30 [log] [ManagerDrivers] [netgear] [0] the internet connection went down 
2019-06-07 16:17:10 [log] [ManagerDrivers] [netgear] [0] the internet connection came up 
2019-06-07 16:16:50 [log] [ManagerDrivers] [netgear] [0] the internet connection went down 
2019-06-07 16:06:40 [log] [MyApp] Router compatibility test started 
2019-06-07 16:06:32 [log] [MyApp] Router discovery started 
2019-06-07 15:42:52 [log] [ManagerDrivers] [netgear] [0] new router firmware installed: V1.2.0.42 
2019-06-07 15:42:52 [log] [ManagerDrivers] [netgear] [0] the internet connection came up 
2019-06-07 15:42:27 [log] [ManagerDrivers] [netgear] [0] Access control enable requested 
2019-06-07 15:42:21 [log] [ManagerDrivers] [netgear] [0] Traffic meter enable requested 
2019-06-07 15:42:21 [log] [ManagerDrivers] [netgear] [0] retrieving knownDevices from persistent storage 
2019-06-07 15:42:21 [log] [ManagerDrivers] [netgear] [0] device init: R6800 id: 4S8882BW0011D 
2019-06-07 15:42:21 [log] [ManagerDrivers] [netgear] NetgearDriver onInit 
2019-06-07 15:35:25 [log] [MyApp] app unload called

**Comment by gruijter** [comment]
This actually looks ok. Maybe you should try to fully delete the app, and then install it again. It should report around 11 devices connected for you.

**Comment by Ikon79** [comment]
Yes, it should be 11.
I’ll try and delete then

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by Ikon79** [comment]
Reinstalled now, devices doesn’t update. 
I left my wi-fi and it still was 11

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
It takes 5 minutes for a device to be reported as offline after disabling the wifi.
After turning on the wifi again, it should be reported as online within one minute.

Are you waiting long enough?

**Comment by Ikon79** [comment]
I changed those settings to 20 sec and 60 sec. 
And also it doesn’t update


Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
Those values are very short. It can lead to multiple problems. Keep them on the default values at first and see if that works well, before fiddling with them.

I saw in your logs that you at least had one device reporting correctly: E4:A7:A0:27:53:BC GT-6341HKJ 192.168.1.13

**Comment by gruijter** [comment]
oh yeah, and also do a ptp (power down and up) of the router! You might have got it in a weird state because of the 20s polling interval.

**Comment by Ikon79** [comment]
I set it back to 60/300
How do i do power down/up. U mean reboot?

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
yes, reboot by physical power down/up (ptp: pull the plug)

**Comment by Ikon79** [comment]
Ok😃. 
Done, didn’t see any change 

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
Are devices still not being reported online/offline correctly? Homey should be able to see the same list as what you see in the Netgear Nighthawk app. Is the Nighthawk app showing something different from Homey?

**Comment by Ikon79** [comment]
It doesn’t show the same. I have 9 online in netgear app (which is also correect) 
And i have ten in Homey



Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
Weird. I would expect to see it in the logs if the devicelist is not read correctly. Do you have only one router in your network, or more? Does your Homey have a fixed ip?

**Comment by Ikon79** [comment]
Homey doesn’t have a fixed IP, but i have never seem it change. 

Yea, there was this crappy router in my apartmemt that was installed in the wall, that my service provider installed. I must use it, so that is set in bridge mode. 

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
I have no clue what is going wrong in your setup. The logs you posted do not show any problem with the devicelist. I will keep this issue open. Let me know if anything changes (fyi: I just updated the app again, but there are no changes that have anything to do with device list)

**Comment by Ikon79** [comment]
Ok, will do

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
I just uploaded v2.5.6  to the appstore for approval by Athom.
It has a fix getAttachedDevices for certain routers. Maybe it solves your issue as well, although I am not sure that it will. 

You can install from github (sideload) or wait for the appstore approval.

Let me know if this indeed fixes your issue or not  :)

**Comment by gruijter** [comment]
oh, and you can also try to set the soap port to 443. This enables the https communication and might be more stable then the http communication.

**Comment by Ikon79** [comment]
Ok, i’ll test. 
Thanks for getting back to me, you are very helpful

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by gruijter** [comment]
Any news / feedback for me @Ikon79 ?

**Comment by Ikon79** [comment]
No, not really, same problems

Med vänlig hälsning, Anders

Skickat från min iPhone

**Comment by ma-be** [comment]
Hi, I think I have the same problem. The Homey app does not refresh the attached devices. There are regular login problems recorded in the log:

2019-10-17 05:16:44 [log] [ManagerDrivers] [netgear] [0] login succsesfull @ driver 
2019-10-17 05:15:44 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in 
2019-10-17 05:15:44 [log] [ManagerDrivers] [netgear] [0] "\r\n\r\n\r\n 401\r\n\r\n\r\n" 
2019-10-17 05:15:44 [log] [ManagerDrivers] [netgear] [0] last repsonse from router: 
2019-10-17 04:20:41 [log] [ManagerDrivers] [netgear] [0] login succsesfull @ driver 
2019-10-17 04:19:39 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in 
2019-10-17 04:19:39 [log] [ManagerDrivers] [netgear] [0] "\r\n\r\n\r\n 401\r\n\r\n\r\n" 
2019-10-17 04:19:39 [log] [ManagerDrivers] [netgear] [0] last repsonse from router: 

The situation:
Router R6350, latest firmware
Homey app, latest stable one

Should be any other info helpful, let me know please.

Thanks.

**Comment by gruijter** [comment]
Hi @ma-be
First try a ptp of the router (power cycle). Secondly you can try with the beta version of the app, but you need to be on Homey v3 for that.

**Comment by ma-be** [comment]
Thanks for the advise @gruijter!

The ptp did not help. I had to uninstall the Netgear app and install it again. I have also installed the iOS Nighthawk app to check the attached devices somewhere else than in web admin console or in Homey app in the settings. After these steps it started to work.

However it looks sometimes that Homey app considers some devices attached even they are far far away and disconnected. On the List tab in settings, the device is listed with current time (and online:true). When I look at the attached devices in admin console or in the Nighthawk ios app, the device is correctly not attached anymore. And then after some time (i.e. 30 minutes) the homey app “decides” that the device is not connected anymore. 

It seems that this happens after the [err] message “not logged in” appears in the log (see my previous comment)... Do you have any idea why this could happen?

Thanks!

**Comment by ma-be** [comment]
PS: I will definitelly try the beta version of your app - it seems to be much better :-). But I do not want to go to experimental Homey firmware. So I will wait a while...

**Comment by gruijter** [comment]
The if the app cannot login to the router for some reason, it will not know that devices went offline or online. The v3 beta app has some improvements on handling login errors with the router. So you might want to try that. But if you want to stay on the stable stream you will have to wait some time.

**Comment by gruijter** [comment]
😂 our comments crossed

**Comment by gruijter** [comment]
@Ikon79 Can you test again with app version 3.0.3 (pending now in the appstore)?

Many compatibility improvements have been introduced in app v3, so I hope it now also works for you. Make sure to do a PTP of the router before AND after pairing it to Homey.

**Comment by gruijter** [comment]
@Ikon79 

New Firmware released by Netgear introduced new problems in parsing attached devices. I have made a new release that can manage these firmware issues, and also fixes some other minor issues.

Netgear package 3.9.9. Fixed fw update on R7000. Fix parsing of <unknown> devices. Fix delete Devicelist. Selectable login method added.

Get it here:
https://homey.app/a/com.gruijter.netgear/test/
